#!/bin/bash
#
# Automatically adds branch name and branch description to every commit message.
#
NAME=$(git branch | grep '*' | sed 's/* //')
DESCRIPTION=$(git config branch."$NAME".description)

MESSAGE=$(cat $1)

echo $MESSAGE | grep -q '\['$NAME'\]'

if [[ $? -ne 0 ]]; then
	echo -n "[$NAME]"' - '|cat - "$1" > /tmp/out && mv /tmp/out "$1"

	if [ -n "$DESCRIPTION" ]
	then
	   echo "" >> "$1"
	   echo $DESCRIPTION >> "$1"
	fi
fi
