#!/bin/bash

protected_branches=("master" "develop" "qa" "release")

remote=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sed 's#^refs/remotes/##' | cut -d'/' -f1)
branch=$(git rev-parse --abbrev-ref HEAD)

if [[ " ${protected_branches[@]} " =~ " ${branch} " ]]; then
    echo "You cannot push changes to the $branch branch. This is a protected branch. Please push your changes to a feature branch and create a pull request instead."
    exit 1
fi

if [[ "$remote" != "origin" && ! "$remote" =~ ^upstream-.*$ && "$remote" != "$branch" ]]; then
    echo "You cannot push changes from $branch to $remote."
    exit 1
fi

exit 0
