#!/bin/sh

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $current_branch = $protected_branch ]; then
  echo '[Policy] Cannot push to '$protected_branch' branch. Please push a feature branch and make a PR.'
  exit 1
fi

unset do_exit

exit 0
